return {
    WINDOW_WIDTH = 1280,
    WINDOW_HEIGHT = 720,
    WORLD_WIDTH = 3000,
    WORLD_HEIGHT = 3000,

    PLANET_RADIUS = 60,
    PLANET_HP = 100,
    PLANET_FRAME_DURATION = 0.08,
    PLANET_FRAME_COUNT = 24,
    PLANET_FRAME_WIDTH = 100,
    PLANET_FRAME_HEIGHT = 100,

    PLAYER_RADIUS = 12,
    PLAYER_SPEED = 300,
    PLAYER_FUEL_MAX = 100,
    PLAYER_FUEL_DRAIN = 5,
    PLAYER_COLOR = { 0.2, 1.0, 0.2 },

    BULLET_RADIUS = 4,
    BULLET_SPEED = 600,
    BULLET_COOLDOWN = 0.2,
    BULLET_COLOR = { 1.0, 1.0, 0.2 },

    BASIC_ENEMY_RADIUS = 14,
    BASIC_ENEMY_SPEED = 80,
    BASIC_ENEMY_HP = 2,
    BASIC_ENEMY_DAMAGE = 10,
    BASIC_ENEMY_COLOR = { 1.0, 0.2, 0.2 },

    FAST_ENEMY_RADIUS = 10,
    FAST_ENEMY_SPEED = 160,
    FAST_ENEMY_HP = 1,
    FAST_ENEMY_DAMAGE = 10,
    FAST_ENEMY_COLOR = { 1.0, 0.5, 0.0 },

    ENEMY_PLANET_RADIUS = 40,
    ENEMY_PLANET_COLOR = { 0.6, 0.1, 0.1 },
    ENEMY_PLANET_SPAWN_INTERVAL = 3.0,
    ENEMY_PLANET_POSITIONS = {
        { x = 400, y = 400 },
        { x = 2600, y = 2600 },
    },

    SCRAP_RADIUS = 5,
    SCRAP_COLOR = { 0.2, 0.2, 1.0 },

    SCRAP_TO_MONEY_RATE = 1,

    DEFENSE_RADIUS_BASE = 150,
    DEFENSE_RADIUS_PER_LEVEL = 50,
    DEFENSE_FIRE_RATE = 1.5,
    DEFENSE_BULLET_SPEED = 400,
    DEFENSE_BULLET_COLOR = { 0.5, 0.0, 1.0 },
    DEFENSE_COST_BASE = 10,
    DEFENSE_COST_UPGRADE = 15,
    DEFENSE_MAX_LEVEL = 3,

    DEBUG = false,
}
