return {
    WINDOW_WIDTH = 1280,
    WINDOW_HEIGHT = 720,

    PLANET_RADIUS = 60,
    PLANET_HP = 100,
    PLANET_COLOR = { 0.2, 0.6, 0.8 },

    PLAYER_RADIUS = 12,
    PLAYER_SPEED = 300,
    PLAYER_COLOR = { 0.2, 1.0, 0.2 },

    BULLET_RADIUS = 4,
    BULLET_SPEED = 600,
    BULLET_COOLDOWN = 0.2,
    BULLET_COLOR = { 1.0, 1.0, 0.2 },

    BASIC_ENEMY_RADIUS = 14,
    BASIC_ENEMY_SPEED = 80,
    BASIC_ENEMY_HP = 2,
    BASIC_ENEMY_DAMAGE = 10,
    BASIC_ENEMY_COLOR = { 1.0, 0.2, 0.2 },

    FAST_ENEMY_RADIUS = 10,
    FAST_ENEMY_SPEED = 160,
    FAST_ENEMY_HP = 1,
    FAST_ENEMY_DAMAGE = 10,
    FAST_ENEMY_COLOR = { 1.0, 0.5, 0.0 },

    SPAWN_INTERVAL = 2.0,
    WAVE_BASE_COUNT = 5,
    WAVE_INCREMENT = 3,
    WAVE_DELAY = 5.0,

    RESOURCE_RADIUS = 5,
    RESOURCE_COLOR = { 0.2, 0.2, 1.0 },

    DEBUG = false,
}
